import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarTop from "@/components/navbarTop";
import Navbar from "@/components/Navbar";
import Product from "@/components/Product";
import Footer from "@/components/Footer";
import MobileNavbar from "@/components/NavbarMobil";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <NavbarTop/>
        <Navbar/>
        {children}
        <Footer/>
        <MobileNavbar/>
      </body>
    </html>
  );
}
